[pytest]
DJANGO_SETTINGS_MODULE = taskhub.config.settings
python_files = test_*.py
addopts = --tb=short -v
testpaths = taskhub/test/services

markers = 
    principal: principais testes da aplicação
    userName: testes para validação de nomes
    enterprise_name: testes para validação de nomes de enterprise
    git_id: testes para validação de id do usuario
    repository_id: testes para validação de id do repositorio
    enterprise_id: testes para validação de id de enterprise
    creator_id: testes para validação de id do criador
    fails: testes para verificar como as exceptions se comportam
    timestamp: teste para conferencia de data e hora
    list_none: verifica se caso o resultado for uma lista vazia a operação se comporta como esperado
    not_found: espera o lançamento de exception domain-not_found
    email: testes que lidam com emails, podem ser erros, ocultos ou verficações
    multiple_entries_missing: testes que lidam com entradas á menos, seu intuito é chamar uma exception
    whitespace: garante que strings validas mesmo com em branco sejam aprovadas
    integration: valida comparações que tendem a vir como response de outro serviço
    invalid_data: testa dados de entrada inválidos
    performance: teste de performance
    security: tetes que de segurança
    now: tests do momento
    unauthorized: testes de usuário não autorizado
    fails_content: testes de falha no content repository
    fails_permission: testes de falha na permissão
    fails_enterprise: testes de exceções de enterprise
    fails_general: testes de exceções gerais
    fails_content: testes de falha no content repository
    fails_permission: testes de falha na permissão
    fails_general: testes de exceções gerais
    edge_cases: validações de casos
    handling_cases: exceções de serviços externos