class AppCode:
    """
    Estrutura de subcódigos de resposta:
    - 1º dígito: Método HTTP
        2 = POST (create)
        3 = PATCH/PUT (update)
        4 = DELETE (delete)
        5 = GET (read)
        6 = AUTH/LOGIN
        7 = FAIL (erros de serviço)
    - 2º e 3º dígitos: Entidade
        10 = User
        20 = Task
        30 = Note
        40 = Enterprise
        50 = Repository
        60 = ContentRepository
        70 = RepositoryPermission
        90 = Chat
    - 4º dígito: Subcódigo de operação
        0 = Operação básica
        1 = Listagem
        2 = Atualização
        3 = Exclusão
        4 = Conflito/Existência
        5 = Não encontrado
    """

    # 2xx - POST / CREATE (Sucesso)
    USER_CREATED = 2100
    TASK_CREATED = 2200
    NOTE_CREATED = 2300
    ENTERPRISE_CREATED = 2400
    REPOSITORY_CREATED = 2500
    CONTENT_REPOSITORY_CREATED = 2600
    REPOSITORY_PERMISSION_CREATED = 2700
    CHAT_STARTED = 2900

    # 3xx - PATCH/PUT / UPDATE (Sucesso)
    USER_UPDATED = 3100
    TASK_UPDATED = 3200
    NOTE_UPDATED = 3300
    ENTERPRISE_UPDATED = 3400
    REPOSITORY_UPDATED = 3500
    CONTENT_REPOSITORY_UPDATED = 3600
    REPOSITORY_PERMISSION_UPDATED = 3700
    CHAT_UPDATED = 3900

    # 4xx - DELETE (Sucesso)
    USER_DELETED = 4100
    TASK_DELETED = 4200
    NOTE_DELETED = 4300
    ENTERPRISE_DELETED = 4400
    REPOSITORY_DELETED = 4500
    CONTENT_REPOSITORY_DELETED = 4600
    REPOSITORY_PERMISSION_DELETED = 4700
    CHAT_ENDED = 4900

    # 5xx - GET / READ (Sucesso)
    USER_DETAIL = 5100
    USER_LIST = 5101
    TASK_DETAIL = 5200
    TASK_LIST = 5201
    NOTE_DETAIL = 5300
    NOTE_LIST = 5301
    ENTERPRISE_DETAIL = 5400
    ENTERPRISE_LIST = 5401
    REPOSITORY_DETAIL = 5500
    REPOSITORY_LIST = 5501
    CONTENT_REPOSITORY_DETAIL = 5600
    CONTENT_REPOSITORY_LIST = 5601
    REPOSITORY_PERMISSION_DETAIL = 5700
    REPOSITORY_PERMISSION_LIST = 5701
    CHAT_HISTORY = 5900

    # 6xx - AUTH / LOGIN
    AUTH_LOGIN_SUCCESS = 6100
    AUTH_LOGOUT_SUCCESS = 6101
    AUTH_JWT_CREATED = 6102
    AUTH_JWT_REFRESHED = 6103
    
    # Erros de autenticação (6x4x)
    AUTH_INVALID_CREDENTIALS = 6401
    AUTH_TOKEN_EXPIRED = 6402
    AUTH_GITHUB_CALLBACK_ERROR = 6501
    AUTH_GITHUB_EMAIL_MISSING = 6502
    AUTH_USER_NOT_FOUND = 6503
    AUTH_USER_ALREADY_EXISTS = 6504

    # 7xx - FAIL SERVICE (Erros de operação)
    # User (71xx)
    USER_CREATE_FAILED = 7100 
    USER_LIST_FAILED = 7101 
    USER_UPDATE_FAILED = 7102 
    USER_DELETE_FAILED = 7103 
    USER_ALREADY_EXISTS = 7104  # Padronizado com sufixo _FAILED
    USER_NOT_FOUND = 7105 
    
    # Task (72xx)
    TASK_CREATE_FAILED = 7200 
    TASK_LIST_FAILED = 7201 
    TASK_UPDATE_FAILED = 7202 
    TASK_DELETE_FAILED = 7203 
    TASK_ALREADY_EXISTS = 7204
    TASK_NOT_FOUND = 7205
    TASK_DETAIL_FAILED = 7206
    
    # Note (73xx)
    NOTE_CREATE_FAILED = 7300 
    NOTE_LIST_FAILED = 7301 
    NOTE_UPDATE_FAILED = 7302 
    NOTE_DELETE_FAILED = 7303 
    NOTE_ALREADY_EXISTS = 7304
    NOTE_NOT_FOUND = 7305
    
    # Enterprise (74xx)
    ENTERPRISE_CREATE_FAILED = 7400 
    ENTERPRISE_LIST_FAILED = 7401 
    ENTERPRISE_UPDATE_FAILED = 7402 
    ENTERPRISE_DELETE_FAILED = 7403 
    ENTERPRISE_ALREADY_EXISTS = 7404
    ENTERPRISE_NOT_FOUND = 7405

    # Repository (75xx)
    REPOSITORY_CREATE_FAILED = 7500 
    REPOSITORY_LIST_FAILED = 7501 
    REPOSITORY_UPDATE_FAILED = 7502 
    REPOSITORY_DELETE_FAILED = 7503 
    REPOSITORY_ALREADY_EXISTS = 7504
    REPOSITORY_NOT_FOUND = 7505
    
    # ContentRepository (76xx)
    CONTENT_REPOSITORY_CREATE_FAILED = 7600 
    CONTENT_REPOSITORY_LIST_FAILED = 7601 
    CONTENT_REPOSITORY_UPDATE_FAILED = 7602 
    CONTENT_REPOSITORY_DELETE_FAILED = 7603 
    CONTENT_REPOSITORY_ALREADY_EXISTS = 7604
    CONTENT_REPOSITORY_NOT_FOUND = 7605
    CONTENT_REPOSITORY_DETAIL_FAILED = 7606
    
    # RepositoryPermission (77xx)
    REPOSITORY_PERMISSION_CREATE_FAILED = 7700 
    REPOSITORY_PERMISSION_LIST_FAILED = 7701 
    REPOSITORY_PERMISSION_UPDATE_FAILED = 7702
    REPOSITORY_PERMISSION_DELETE_FAILED = 7703
    REPOSITORY_PERMISSION_ALREADY_EXISTS = 7704
    REPOSITORY_PERMISSION_NOT_FOUND = 7705

    # Chat (79xx)
    CHAT_CREATE_FAILED = 7900 
    CHAT_LIST_FAILED = 7901 
    CHAT_UPDATE_FAILED = 7902 
    CHAT_DELETE_FAILED = 7903
    CHAT_ALREADY_EXISTS = 7904
    CHAT_NOT_FOUND = 7905

    # ADD USER AND PERMISSIONS(80xx and 81xx)
    USER_ADDED_ENTERPRISE = 8000
    USER_ADDED_PERMISSIONS = 8100


    #FAIL(85xx and 86xx)
    USER_ADDED_ENTERPRISE_FAILED = 8500
    USER_ADDED_PERMISSION_FAILED = 8600

    
    ENTERPRISE_REMOVE_USER_FAILED = 8504
    ENTERPRISE_REMOVE_PERMISSION_FAILED = 8604


    INPUT_EXCEEDED_CHARACTER_LIMIT = 9000

from rest_framework.status import (
    HTTP_400_BAD_REQUEST,
    HTTP_401_UNAUTHORIZED,
    HTTP_403_FORBIDDEN,
    HTTP_404_NOT_FOUND, 
    HTTP_409_CONFLICT, 
    HTTP_500_INTERNAL_SERVER_ERROR,
    HTTP_503_SERVICE_UNAVAILABLE
)

class ErrorsAppStatus:
    """
    Mapeamento de códigos HTTP padrão para erros da aplicação
    """
    BAD_REQUEST = HTTP_400_BAD_REQUEST
    UNAUTHORIZED = HTTP_401_UNAUTHORIZED
    FORBIDDEN = HTTP_403_FORBIDDEN
    NOT_FOUND = HTTP_404_NOT_FOUND
    CONFLICT = HTTP_409_CONFLICT
    SERVER_ERROR = HTTP_500_INTERNAL_SERVER_ERROR
    SERVICE_UNAVAILABLE = HTTP_503_SERVICE_UNAVAILABLE